doctrine:
    dbal:
        schema_filter: ~^(?!event)~ # this will ignore broadway event store table
        url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_mysql
        charset: utf8mb4
        server_version: '8.0.33'
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
          email: App\Shared\Infrastructure\Persistence\Doctrine\Types\EmailType
          hashed_password: App\Shared\Infrastructure\Persistence\Doctrine\Types\HashedPasswordType
        mapping_types:
          uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/user'
                prefix: 'App\User'
                alias: App
